#!/bin/bash

###
# Bootstrapping script
#
# Current unboxing time - 0:50
# Dependencies
# - Xcode
# - MAMP
# - Sublime Text 3
###

# Setup ------------------------------------------------------------ /

# Ask password upfront
sudo -v

DOTFILES=~/dotfiles
PACKAGES=$DOTFILES/scripts/packages
VENDOR=$DOTFILES/vendor

# Load colorized output
source $DOTFILES/helpers/colorizer.sh

# Commands --------------------------------------------------------- /

case "$1" in

  # Install dependencies
  setup)
    source $DOTFILES/scripts/setup.sh
  ;;

  # Upgrade core files
  upgrade)
    source $DOTFILES/scripts/upgrade.sh
  ;;

  # Update and sync dependencies
  update)
    source $DOTFILES/scripts/upgrade.sh
    source $DOTFILES/scripts/update.sh
  ;;

  # Remove Dotfiler
  uninstall)
    ruby $DOTFILES/scripts/uninstall.rb
  ;;

  # Reinstall Dotfiler
  reinstall)
    source $DOTFILES/scripts/uninstall.sh
    source $DOTFILES/scripts/setup.sh
    source $DOTFILES/scripts/update.sh
  ;;

  # Help
  *)
    info "Dotfiler - Setup and upgrade helper"
    info "      dotfiler setup     - Setup dotfiler and its dependencies"
    info "      dotfiler update    - Update Dotfiler and its dependencies"
    info "      dotfiler upgrade   - Update Dotfiler itself"
    info "      dotfiler uninstall - Remove Dotfiler"
  ;;
esac
