#!/bin/bash

###
# Bootstrapping script
#
# Current unboxing time - 0:50
# Dependencies
# - Xcode
# - MAMP
# - Sublime Text 3
###

# Setup ------------------------------------------------------------ /

# Ask password upfront
sudo -v

DOTFILES=~/dotfiles
PACKAGES=$DOTFILES/scripts/packages

# Load colorized output
source $DOTFILES/helpers/colorizer.sh
header "Foobar"
subheader "caca"

# Commands --------------------------------------------------------- /

case "$1" in

  # Install dependencies
  setup)
    if [ ! -f "$HOME/.aliases" ]; then
      source $DOTFILES/scripts/setup.sh
    fi
  ;;

  # Upgrade core files
  upgrade)
    source $DOTFILES/scripts/upgrade.sh
  ;;

  # Update and sync dependencies
  update)
    source $DOTFILES/scripts/upgrade.sh
    source $DOTFILES/scripts/update.sh
  ;;

  # Remove Dotfiler
  uninstall)
    source $DOTFILES/scripts/uninstall.sh
  ;;

  # Reinstall Dotfiler
  reinstall)
    source $DOTFILES/scripts/uninstall.sh
    source $DOTFILES/scripts/setup.sh
    source $DOTFILES/scripts/update.sh
  ;;
esac
