#!/bin/bash

###
# Bootstrapping script
#
# Current unboxing time - 0:50
# Dependencies
# - Xcode
# - Sublime Text 3
###

# Setup ------------------------------------------------------------ /

# Ask password upfront
sudo -v

# Create some shortcuts to core folders
DOTFILES=~/dotfiles
PACKAGES=$DOTFILES/scripts/packages
VENDOR=$DOTFILES/vendor
WORK=/Users/anahkiasen/Sites

# Load helpers
source $DOTFILES/helpers/colorizer.sh
source $DOTFILES/helpers/functions.sh

# Commands --------------------------------------------------------- /

case "$1" in

  # Install dependencies
  setup)
    source $DOTFILES/scripts/setup.sh
  ;;

  grunt)
    source $DOTFILES/scripts/grunt.sh
  ;;

  # Help
  *)
    info "Dotfiler - Setup and upgrade helper"
    info "      dotfiler setup     - Setup dotfiler and its dependencies"
  ;;
esac
